[package]
name = "mc-crypto-hashes"
version = "1.2.0-pre0"
authors = ["MobileCoin"]
edition = "2018"

[dependencies]
blake2 = { version = "0.10.2", default-features = false, features = ["simd"] }
digest = "0.10.1"

mc-crypto-digestible = { path = "../digestible" }
