// Copyright (c) 2018-2022 The MobileCoin Foundation

//! MobileCoin gRPC API.

mod autogenerated_code {
    // Expose proto data types from included third-party/external proto files.
    pub use protobuf::well_known_types::empty;

    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}

pub mod convert;
pub mod display;

pub use crate::{
    autogenerated_code::*,
    convert::{block_num_to_s3block_path, merged_block_num_to_s3block_path, ConversionError},
};
