[package]
name = "mc-util-parse"
version = "1.3.0-pre0"
authors = ["MobileCoin"]
edition = "2021"
description = "Helpers for parsing, particularly, for use with Clap and similar"
readme = "README.md"

[dependencies]
mc-sgx-css = { path = "../../sgx/css" }

duration-str = "0.3"
itertools = "0.10"
