[package]
name = "mc-ledger-streaming-client"
version = "1.3.0-pre0"
authors = ["MobileCoin"]
license = "MIT OR Apache-2.0"
edition = "2018"

[features]
test_utils = []

[dependencies]
mc-api = { path = "../../../api" }
mc-common = { path = "../../../common" }
mc-consensus-scp = { path = "../../../consensus/scp" }
mc-crypto-keys = { path = "../../../crypto/keys" }
mc-ledger-db = { path = "../../../ledger/db" }
mc-ledger-streaming-api = { path = "../api" }
mc-ledger-streaming-publisher = { path = "../publisher" }
mc-transaction-core = { path = "../../../transaction/core" }
mc-util-grpc = { path = "../../../util/grpc" }
mc-util-uri = { path = "../../../util/uri" }

displaydoc = "0.2"
futures = { version = "0.3", features = ["thread-pool"] }
grpcio = "0.10"
protobuf = "2.22"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "gzip"] }
tokio = { version = "1.16.0", optional = true }
url = "2.2"

[dev-dependencies]
mc-common = { path = "../../../common", features = ["loggers"] }
mc-ledger-db = { path = "../../../ledger/db", features = ["test_utils"] }
mc-ledger-streaming-api = { path = "../api", features = ["test_utils"] }
mc-util-from-random = { path = "../../../util/from-random" }

mockito = "0.31"
rand_core = "0.6"
rand_hc = "0.3"
tokio = { version = "1.16", features = ["macros", "rt-multi-thread"] }
